import 'skill_data.dart';
export 'skill_data.dart';

enum SystemType { normal, elite, boss }

class SecurityProgram {
  final String id;
  final String name;
  final SystemType type;
  final int level;
  final int maxHp;
  final int baseDamage;
  final int damageMin;
  final int damageMax;
  final String description;
  final List<String> skillIds;
  
  const SecurityProgram({
    required this.id,
    required this.name,
    required this.type,
    required this.level,
    required this.maxHp,
    required this.baseDamage,
    required this.damageMin,
    required this.damageMax,
    required this.description,
    this.skillIds = const [],
  });

  /// 获取对应的技能对象列表
  List<MonsterSkill> get skills => skillIds.map((id) => skillDatabase[id]!).toList();
}

/// 系统防护程序数据库
const Map<String, SecurityProgram> systemDatabase = {
  "slime": SecurityProgram(
    id: "slime",
    name: "粘滞碎片",
    type: SystemType.normal,
    level: 1,
    maxHp: 40,
    baseDamage: 8,
    damageMin: 6,
    damageMax: 10,
    description: "一团具有粘性的数据残留，会拖慢系统的响应速度",
    skillIds: ["jam"],
  ),
  "goblin": SecurityProgram(
    id: "goblin",
    name: "窥探程序",
    type: SystemType.normal,
    level: 1,
    maxHp: 30,
    baseDamage: 10,
    damageMin: 8,
    damageMax: 12,
    description: "细小且灵活的程序，在系统角落里寻找任何可利用的缝隙",
    skillIds: ["probe", "strain"],
  ),
  "skeleton": SecurityProgram(
    id: "skeleton",
    name: "废弃指令",
    type: SystemType.normal,
    level: 2,
    maxHp: 25,
    baseDamage: 12,
    damageMin: 10,
    damageMax: 14,
    description: "早已被淘汰的旧版代码，即便残破不堪仍在机械地执行最后的任务",
    skillIds: ["infect"],
  ),
  "orc_warrior": SecurityProgram(
    id: "orc_warrior",
    name: "重装守卫",
    type: SystemType.elite,
    level: 3,
    maxHp: 60,
    baseDamage: 15,
    damageMin: 13,
    damageMax: 18,
    description: "配备了厚重防御装甲的安保程序，是任何渗透者的噩梦",
    skillIds: ["crush", "fortify"],
  ),
  "dark_mage": SecurityProgram(
    id: "dark_mage",
    name: "幽暗影",
    type: SystemType.elite,
    level: 4,
    maxHp: 45,
    baseDamage: 18,
    damageMin: 16,
    damageMax: 20,
    description: "如阴影般潜伏在内存深处，能悄无声息地夺走系统的活力",
    skillIds: ["drain"],
  ),
  "dragon": SecurityProgram(
    id: "dragon",
    name: "裁决者",
    type: SystemType.boss,
    level: 5,
    maxHp: 150,
    baseDamage: 25,
    damageMin: 22,
    damageMax: 30,
    description: "系统最高层级的执行者，拥有决定任何数据生死存亡的终极权力",
    skillIds: ["lock", "pressure", "expose"],
  ),
  // 新增更易理解和顺口的怪兽
  "echo_bug": SecurityProgram(
    id: "echo_bug",
    name: "回响单元",
    type: SystemType.normal,
    level: 2,
    maxHp: 35,
    baseDamage: 8,
    damageMin: 6,
    damageMax: 10,
    description: "不断重复接收到的信号，造成严重的逻辑循环干扰",
    skillIds: ["repeat"],
  ),
  "spark_ball": SecurityProgram(
    id: "spark_ball",
    name: "电脉冲",
    type: SystemType.normal,
    level: 2,
    maxHp: 30,
    baseDamage: 12,
    damageMin: 10,
    damageMax: 14,
    description: "极度不稳定的能量球，任何接触都可能导致系统瞬间过载",
    skillIds: ["shock"],
  ),
  "iron_dummy": SecurityProgram(
    id: "iron_dummy",
    name: "铁甲",
    type: SystemType.normal,
    level: 1,
    maxHp: 88,
    baseDamage: 6,
    damageMin: 1,
    damageMax: 4,
    description: "笨重但极其坚固的冗余模块，常被用作物理屏障",
    skillIds: ["heavy_slam"],
  ),
  "shadow_hunter": SecurityProgram(
    id: "shadow_hunter",
    name: "潜行猎手",
    type: SystemType.elite,
    level: 3,
    maxHp: 75,
    baseDamage: 18,
    damageMin: 15,
    damageMax: 22,
    description: "专门猎杀异常数据的暗杀程序，擅长从视觉死角发起攻击",
    skillIds: ["backstab", "hide"],
  ),
  "scythe_hand": SecurityProgram(
    id: "scythe_hand",
    name: "收割指令",
    type: SystemType.elite,
    level: 4,
    maxHp: 85,
    baseDamage: 20,
    damageMin: 18,
    damageMax: 24,
    description: "挥舞着巨大的清理工具，将一切不符合规范的代码统统切碎",
    skillIds: ["reap"],
  ),
  "grand_manager": SecurityProgram(
    id: "grand_manager",
    name: "主控核心",
    type: SystemType.boss,
    level: 5,
    maxHp: 200,
    baseDamage: 30,
    damageMin: 25,
    damageMax: 35,
    description: "整个系统的神经中枢，它的每一次波动都足以改写底层的运行逻辑",
    skillIds: ["format", "reboot", "optimize"],
  ),
  "casino_boss": SecurityProgram(
    id: "casino_boss",
    name: "赌场经理",
    type: SystemType.boss,
    level: 5,
    maxHp: 200,
    baseDamage: 20,
    damageMin: 18,
    damageMax: 22,
    description: "掌握着赌场所有核心算力的管理者，能够源源不断地调度安保程序。",
    skillIds: ["summon"],
  ),
  "casino_security": SecurityProgram(
    id: "casino_security",
    name: "赌场保镖",
    type: SystemType.normal,
    level: 3,
    maxHp: 50,
    baseDamage: 12,
    damageMin: 10,
    damageMax: 15,
    description: "赌场的精英安保程序，专门处理强行闯入的渗透者。",
    skillIds: ["lockdown"],
  ),
  "curse_monster": SecurityProgram(
    id: "curse_monster",
    name: "禁锢者",
    type: SystemType.elite,
    level: 3,
    maxHp: 70,
    baseDamage: 10,
    damageMin: 8,
    damageMax: 12,
    description: "通过植入特殊的锁定协议来限制敌人的行动。",
    skillIds: ["curse_lock"],
  ),
  // 枯竭国度的新怪兽
  "void_leech": SecurityProgram(
    id: "void_leech",
    name: "虚空水蛭",
    type: SystemType.normal,
    level: 2,
    maxHp: 35,
    baseDamage: 9,
    damageMin: 7,
    damageMax: 11,
    description: "依附在已损毁的数据簇上，贪婪地吸食残存的算力",
    skillIds: ["siphon"],
  ),
  "entropy_shade": SecurityProgram(
    id: "entropy_shade",
    name: "熵影",
    type: SystemType.normal,
    level: 3,
    maxHp: 45,
    baseDamage: 14,
    damageMin: 12,
    damageMax: 16,
    description: "系统熵增的具象化产物，所到之处秩序崩塌",
    skillIds: ["decay"],
  ),
  "null_beast": SecurityProgram(
    id: "null_beast",
    name: "虚无巨兽",
    type: SystemType.elite,
    level: 4,
    maxHp: 90,
    baseDamage: 22,
    damageMin: 18,
    damageMax: 26,
    description: "从数据黑洞中诞生的庞然大物，能吞噬一切碰触到的代码",
    skillIds: ["void_crush", "consume"],
  ),
  "hollow_king": SecurityProgram(
    id: "hollow_king",
    name: "枯竭之王",
    type: SystemType.boss,
    level: 5,
    maxHp: 220,
    baseDamage: 32,
    damageMin: 28,
    damageMax: 36,
    description: "统治着废弃扇区的古老核心，它的存在本身就是对系统资源的极致掠夺",
    skillIds: ["drought", "famine", "desolation"],
  ),
};
