// card_data.dart

/// 卡牌类型枚举
enum CardType { exploit, encryption, routine, module }

/// 卡牌使用目标枚举
enum CardTarget { enemy, self, all }

/// 卡牌数据模型
class CardData {
  final String id;
  final String name;
  final CardType type;
  final CardTarget target; // 使用目标：enemy-敌人，self-自己，all-全体
  final int cost;
  final int value;
  final int level;
  final String? effect; // 效果描述字符串
  final String? description; // UI 显示的描述文字

  const CardData({
    required this.id,
    required this.name,
    required this.type,
    required this.target,
    required this.cost,
    required this.value,
    required this.level,
    this.effect,
    this.description,
  });
}

/// 卡牌实例，用于区分同名卡牌
class CardInstance {
  final String id; // 对应 CardData 的 id
  final String instanceId; // 唯一实例 ID

  CardInstance({required this.id, required this.instanceId});

  CardData? get data => cardDatabase[id];

  static int _counter = 0;
  static CardInstance create(String id) {
    _counter++;
    return CardInstance(
      id: id,
      instanceId: "${id}_${DateTime.now().microsecondsSinceEpoch}_$_counter",
    );
  }
}

/// 卡牌数据库
const Map<String, CardData> cardDatabase = {
  'strike_1': CardData(
    id: 'strike_1',
    name: '数据冲击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 1,
    value: 6,
    level: 1,
    effect: 'damage 6',
    description: '对目标系统造成 6 点冲击。',
  ),
  'strike_2': CardData(
    id: 'strike_2',
    name: '数据冲击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 1,
    value: 6,
    level: 1,
    effect: 'damage 6',
    description: '对目标系统造成 6 点冲击。',
  ),
  'multi_effect_card': CardData(
    id: 'multi_effect_card',
    name: '复合指令集',
    type: CardType.routine,
    target: CardTarget.enemy,
    cost: 2,
    value: 0,
    level: 1,
    effect: 'damage 8; block 5; draw 2',
    description: '造成 8 点冲击，获得 5 点防火墙加固，并读取 2 个数据包。',
  ),
  'defend_1': CardData(
    id: 'defend_1',
    name: '加密协议',
    type: CardType.encryption,
    target: CardTarget.self,
    cost: 1,
    value: 5,
    level: 1,
    effect: 'block 5',
    description: '获得 5 点防火墙加固。',
  ),
  'defend_2': CardData(
    id: 'defend_2',
    name: '硬核防火墙',
    type: CardType.encryption,
    target: CardTarget.self,
    cost: 2,
    value: 12,
    level: 2,
    effect: 'block 12',
    description: '获得 12 点防火墙加固。',
  ),
  'bash': CardData(
    id: 'bash',
    name: '系统中断',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 2,
    value: 8,
    level: 1,
    effect: 'damage 8; vulnerable 2',
    description: '造成 8 点冲击，并施加 2 层漏洞暴露。',
  ),
  'heavy_blade': CardData(
    id: 'heavy_blade',
    name: '暴力破解',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 2,
    value: 14,
    level: 1,
    effect: 'damage 14; strength 2',
    description: '造成 14 点冲击，获得 2 点算力提升。',
  ),
  'double_hit': CardData(
    id: 'double_hit',
    name: '并行冲击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 1,
    value: 4,
    level: 1,
    effect: 'damage 4; damage 4',
    description: '执行两次冲击，每次造成 4 点伤害。',
  ),
  'ritual': CardData(
    id: 'ritual',
    name: '递归算法',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 0,
    value: 3,
    level: 1,
    effect: 'strength 3; self_damage 3',
    description: '获得 3 点算力，但会导致系统过热造成 3 点自损伤。',
  ),
  'sneaky_strike': CardData(
    id: 'sneaky_strike',
    name: '漏洞扫描',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 1,
    value: 4,
    level: 1,
    effect: 'damage 4; draw 1',
    description: '造成 4 点冲击，并读取 1 个数据包。',
  ),
  'defensive_stance': CardData(
    id: 'defensive_stance',
    name: '安全模式',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 1,
    value: 5,
    level: 1,
    effect: 'block 5; strength 1',
    description: '获得 5 点防火墙，并提升 1 点算力。',
  ),
  'desperate_power': CardData(
    id: 'desperate_power',
    name: '紧急过载',
    type: CardType.module,
    target: CardTarget.self,
    cost: 3,
    value: 3,
    level: 1,
    effect: 'strength 2; self_damage 5',
    description: '大幅提升 2 点算力，但系统负载过高造成 5 点自损伤。',
  ),
  'bludgeon': CardData(
    id: 'bludgeon',
    name: '逻辑炸弹',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 3,
    value: 32,
    level: 1,
    effect: 'damage 32',
    description: '投放逻辑炸弹，对目标造成 32 点巨大冲击。',
  ),
  'reaper': CardData(
    id: 'reaper',
    name: '资源回收',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 4,
    value: 4,
    level: 1,
    effect: 'damage 4; heal 2',
    description: '造成 4 点冲击，并从目标回收资源修复 2 点系统完整性。',
  ),
  'burning_slash': CardData(
    id: 'burning_slash',
    name: '超频攻击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 1,
    value: 9,
    level: 1,
    effect: 'damage 9; self_damage 3',
    description: '超频执行攻击造成 9 点冲击，自身受损 3 点。',
  ),
  'ignite': CardData(
    id: 'ignite',
    name: '核心激活',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 0,
    value: 2,
    level: 1,
    effect: 'strength 2; self_damage 2',
    description: '激活核心提升 2 点算力，受损 2 点。',
  ),
  'weaken': CardData(
    id: 'weaken',
    name: '性能限制',
    type: CardType.routine,
    target: CardTarget.enemy,
    cost: 1,
    value: 2,
    level: 1,
    effect: 'weak 2',
    description: '限制目标性能，施加 2 层虚弱状态。',
  ),
  'curse_mark': CardData(
    id: 'curse_mark',
    name: '恶意标记',
    type: CardType.routine,
    target: CardTarget.enemy,
    cost: 1,
    value: 0,
    level: 1,
    effect: 'vulnerable 2; weak 1',
    description: '在目标系统留下恶意标记，施加 2 层漏洞暴露和 1 层虚弱。',
  ),
  'fade_step': CardData(
    id: 'fade_step',
    name: '隐匿跳跃',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 1,
    value: 6,
    level: 1,
    effect: 'block 6; draw 1',
    description: '获得 6 点防火墙，并读取 1 个数据包。',
  ),
  'core_module': CardData(
    id: 'core_module',
    name: '底层内核',
    type: CardType.module,
    target: CardTarget.self,
    cost: 1,
    value: 1,
    level: 1,
    effect: 'strength 1',
    description: '加载底层内核模块，永久提升 1 点算力。',
  ),
  'assemble': CardData(
    id: 'assemble',
    name: '指令编译',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 1,
    value: 2,
    level: 1,
    effect: 'draw 2',
    description: '编译指令流，读取 2 个数据包。',
  ),
  'overclock': CardData(
    id: 'overclock',
    name: '频率超限',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 0,
    value: 1,
    level: 1,
    effect: 'energy 1; self_damage 4',
    description: '强行提升系统频率，获得 1 点带宽，受损 4 点。',
  ),
  'phase_shift': CardData(
    id: 'phase_shift',
    name: '进程迁移',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 1,
    value: 7,
    level: 1,
    effect: 'block 7; draw 1',
    description: '迁移关键进程，获得 7 点防火墙并读取 1 个数据包。',
  ),
  'peek_future': CardData(
    id: 'peek_future',
    name: '预读缓冲区',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 0,
    value: 5,
    level: 1,
    effect: 'draw 1',
    description: '预读数据流，读取 1 个数据包。',
  ),
  'vanish': CardData(
    id: 'vanish',
    name: '清除足迹',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 2,
    value: 18,
    level: 1,
    effect: 'block 18',
    description: '清除系统访问足迹，获得 18 点防火墙。',
  ),
  'survivor': CardData(
    id: 'survivor',
    name: '容错机制',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 0,
    value: 5,
    level: 1,
    effect: 'block 5; draw 1',
    description: '激活容错机制，获得 5 点防火墙并读取 1 个数据包。',
  ),
  'dualcast': CardData(
    id: 'dualcast',
    name: '双线程执行',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 1,
    value: 0,
    level: 1,
    effect: 'draw 2; energy 1',
    description: '开启双线程，读取 2 个数据包并获得 1 点带宽。',
  ),
  'energy_boost': CardData(
    id: 'energy_boost',
    name: '带宽扩容',
    type: CardType.module,
    target: CardTarget.self,
    cost: 1,
    value: 1,
    level: 1,
    effect: 'energy 1',
    description: '扩容系统带宽，获得 1 点额外带宽。',
  ),
  'eruption': CardData(
    id: 'eruption',
    name: '数据喷发',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 3,
    value: 20,
    level: 1,
    effect: 'damage 20',
    description: '瞬间喷发海量数据，对目标造成 20 点冲击。',
  ),
  // Lv2 卡牌
  'data_storm': CardData(
    id: 'data_storm',
    name: '数据风暴',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 2,
    value: 5,
    level: 2,
    effect: 'damage 5; damage 5; damage 5',
    description: '发起三次数据冲击，每次造成 5 点伤害。',
  ),
  'hardened_shell': CardData(
    id: 'hardened_shell',
    name: '强化外壳',
    type: CardType.encryption,
    target: CardTarget.self,
    cost: 2,
    value: 15,
    level: 2,
    effect: 'block 15',
    description: '部署强化外壳，获得 15 点防火墙。',
  ),
  'neural_interface': CardData(
    id: 'neural_interface',
    name: '神经接口',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 2,
    value: 0,
    level: 2,
    effect: 'draw 3; energy 1',
    description: '建立神经连接，读取 3 个数据包并获得 1 点带宽。',
  ),
  'predator_program': CardData(
    id: 'predator_program',
    name: '捕食者程序',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 3,
    value: 12,
    level: 2,
    effect: 'damage 12; heal 5',
    description: '运行捕食者程序，造成 12 点冲击并回收 5 点系统完整性。',
  ),
  'logic_gate': CardData(
    id: 'logic_gate',
    name: '逻辑锁死',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 2,
    value: 10,
    level: 2,
    effect: 'damage 10; vulnerable 3',
    description: '对目标进行逻辑锁死，造成 10 点冲击并施加 3 层漏洞暴露。',
  ),
  'malware_injection': CardData(
    id: 'malware_injection',
    name: '恶意代码注入',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 1,
    value: 5,
    level: 2,
    effect: 'damage 5; curse 2',
    description: '注入一段恶意代码，造成 5 点冲击并施加 2 层恶意代码（每层使目标多受 2 点伤害）。',
  ),
  // Lv3 卡牌
  'singularity': CardData(
    id: 'singularity',
    name: '数据奇点',
    type: CardType.exploit,
    target: CardTarget.enemy,
    cost: 4,
    value: 45,
    level: 3,
    effect: 'damage 45',
    description: '创造一个数据奇点，对目标造成 45 点毁灭性冲击。',
  ),
  'mainframe_hijack': CardData(
    id: 'mainframe_hijack',
    name: '主机劫持',
    type: CardType.routine,
    target: CardTarget.enemy,
    cost: 3,
    value: 20,
    level: 3,
    effect: 'damage 20; draw 4; energy 2',
    description: '劫持对方主机，造成 20 点冲击，读取 4 个数据包并获得 2 点带宽。',
  ),
  'absolute_zero_ice': CardData(
    id: 'absolute_zero_ice',
    name: '绝对零度冰墙',
    type: CardType.encryption,
    target: CardTarget.self,
    cost: 3,
    value: 30,
    level: 3,
    effect: 'block 30',
    description: '部署绝对零度防御系统，获得 30 点防火墙。',
  ),
  'infinite_loop': CardData(
    id: 'infinite_loop',
    name: '无限循环',
    type: CardType.module,
    target: CardTarget.self,
    cost: 2,
    value: 5,
    level: 3,
    effect: 'strength 5; self_damage 10',
    description: '强行开启无限循环模式，提升 5 点算力，但导致系统严重过热受损 10 点。',
  ),
  'system_reboot': CardData(
    id: 'system_reboot',
    name: '系统重装',
    type: CardType.routine,
    target: CardTarget.self,
    cost: 4,
    value: 15,
    level: 3,
    effect: 'heal 15; block 20',
    description: '执行系统重装流程，修复 15 点完整性并部署 20 点防火墙。',
  ),
  'supercomputer_f': CardData(
    id: 'supercomputer_f',
    name: '超算行动-失败',
    type: CardType.module,
    target: CardTarget.self,
    cost: 3,
    value: 5,
    level: 6,
    effect: 'strength 99; self_damage 60',
    description: '强行开启无限循环模式，提升 99 点算力，但导致系统严重过热受损 60 点。',
  ),
};
