// card_data.dart
// 作用：卡牌数据与效果DSL定义
// 效果说明：
// damage        -> 造成伤害
// block         -> 获得防御
// draw          -> 抽取卡牌
// energy        -> 获得能量/带宽
// vulnerable    -> 施加脆弱
// weak          -> 施加虚弱
// curse         -> 施加恶意代码
// strength      -> 获得算力（持久）
// temp_strength -> 获得临时算力（回合开始-5）
// sturdy        -> 获得坚固（护盾回合结束不清零，每回合-1）
// self_damage   -> 自损伤害
// heal          -> 恢复生命
// max_hp_up     -> 增加生命值上限
// max_hp_down   -> 减少生命值上限
//
// 关键区域：上述DSL关键字需与战斗页执行器保持一致

/// 卡牌类型枚举
enum CardType { exploit, encryption, routine, module }

/// 卡牌使用目标枚举
enum CardTarget { enemy, self, all }

/// 卡牌视觉套装枚举
enum CardSuite { 
  classic,    // 经典霓虹
  overload,   // 红色过载/故障
  secure,     // 淡紫终端/安全系统
  industrial, // 工业橙/机械
  quantum,    // 量子紫/虚空
  demon,      // 恶魔/独特样式
  holy        // 神圣/高亮样式
}

/// 卡牌数据模型
class CardData {
  final String id;
  final String name;
  final CardType type;
  final CardTarget target; // 使用目标：enemy-敌人，self-自己，all-全体
  final CardSuite suite;   // 视觉风格套装
  final int cost;
  final int level;
  final String? effect; // 效果描述字符串
  final String? description; // UI 显示的描述文字

  const CardData({
    required this.id,
    required this.name,
    required this.type,
    required this.target,
    this.suite = CardSuite.classic,
    required this.cost,
    required this.level,
    this.effect,
    this.description,
  });
}

/// 卡牌实例，用于区分同名卡牌
class CardInstance {
  final String id; // 对应 CardData 的 id
  final String instanceId; // 唯一实例 ID

  CardInstance({required this.id, required this.instanceId});

  CardData? get data => cardDatabase[id];

  static int _counter = 0;
  static CardInstance create(String id) {
    _counter++;
    return CardInstance(
      id: id,
      instanceId: "${id}_${DateTime.now().microsecondsSinceEpoch}_$_counter",
    );
  }
}

/// 卡牌数据库
const Map<String, CardData> cardDatabase = {
  // --- 职业基础卡牌 (重制版) ---
  
  // 血液 (xueye) - 自残/力量/吸血
  'xueye_strike': CardData(
    id: 'xueye_strike',
    name: '鲜血冲击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.overload,
    cost: 1,
    level: 2,
    effect: 'damage 11; self_damage 2',
    description: '造成 11 点伤害，自身受损 2 点。',
  ),
  'xueye_defend': CardData(
    id: 'xueye_defend',
    name: '血液护盾',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 1,
    level: 3,
    effect: 'block 10; self_damage 1',
    description: '获得 10 点防御，自身受损 1 点。',
  ),
  'xueye_siphon': CardData(
    id: 'xueye_siphon',
    name: '生命虹吸',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.overload,
    cost: 1,
    level: 2,
    effect: 'damage 6; heal 3',
    description: '造成 6 点伤害并回收 3 点生命值。',
  ),

  // 林 (lin) - 抽牌/稳定
  'lin_strike': CardData(
    id: 'lin_strike',
    name: '精准扫描',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.secure,
    cost: 1,
    level: 1,
    effect: 'damage 5; draw 1',
    description: '造成 5 点伤害，读取 1 个数据包。',
  ),
  'lin_defend': CardData(
    id: 'lin_defend',
    name: '冗余备份',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 1,
    level: 1,
    effect: 'block 5; draw 1',
    description: '获得 5 点防御，读取 1 个数据包。',
  ),

  // 浪潮 (langchao) - 能量/多段
  'langchao_strike': CardData(
    id: 'langchao_strike',
    name: '脉冲双击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 1,
    level: 1,
    effect: 'damage 4; damage 4',
    description: '执行两次 4 点伤害的脉冲冲击。',
  ),
  'langchao_defend': CardData(
    id: 'langchao_defend',
    name: '波纹屏障',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.quantum,
    cost: 1,
    level: 1,
    effect: 'block 4; energy 1',
    description: '获得 4 点防御和 1 点带宽。',
  ),

  // 剑刃 (jianren) - 高额伤害
  'jianren_strike': CardData(
    id: 'jianren_strike',
    name: '重型劈砍',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 1,
    level: 2,
    effect: 'damage 9',
    description: '造成 9 点沉重伤害。',
  ),
  'jianren_defend': CardData(
    id: 'jianren_defend',
    name: '装甲加固',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.industrial,
    cost: 1,
    level: 2,
    effect: 'block 8',
    description: '获得 8 点高强度防御。',
  ),

  // 焰心 (yanxin) - 极端过载
  'yanxin_strike': CardData(
    id: 'yanxin_strike',
    name: '炽热注入',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.overload,
    cost: 1,
    level: 1,
    effect: 'damage 14; self_damage 4',
    description: '造成 14 点高额伤害，自身受损 4 点。',
  ),
  'yanxin_defend': CardData(
    id: 'yanxin_defend',
    name: '热能转化',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 1,
    level: 2,
    effect: 'block 6; strength 1',
    description: '获得 6 点防御并提升 1 点算力。',
  ),

  // 影誓 (yingshi) - 控制/虚弱
  'yingshi_strike': CardData(
    id: 'yingshi_strike',
    name: '暗影侵蚀',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 1,
    level: 2,
    effect: 'damage 6; weak 1',
    description: '造成 6 点伤害并施加 1 层虚弱。',
  ),
  'yingshi_defend': CardData(
    id: 'yingshi_defend',
    name: '幽影帷幕',
    type: CardType.encryption,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 1,
    level: 2, 
    effect: 'block 5; vulnerable 1',
    description: '获得 5 点防御并使指定敌方暴露 1 层漏洞。',
  ),

  // 机核 (jihe) - 长期成长
  'jihe_strike': CardData(
    id: 'jihe_strike',
    name: '迭代冲击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 1,
    level: 2,
    effect: 'damage 5; strength 1',
    description: '造成 5 点伤害并提升 1 点算力。',
  ),
  'jihe_defend': CardData(
    id: 'jihe_defend',
    name: '模块加固',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.industrial,
    cost: 1,
    level: 2,
    effect: 'block 7',
    description: '获得 7 点防御。',
  ),

  // 虚行者 (xuxing) - 闪避/预读
  'xuxing_strike': CardData(
    id: 'xuxing_strike',
    name: '幻影突袭',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.secure,
    cost: 1,
    level: 1,
    effect: 'damage 6; draw 1',
    description: '造成 6 点伤害并预读 1 个数据包。',
  ),
  'xuxing_defend': CardData(
    id: 'xuxing_defend',
    name: '虚空闪避',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 1,
    level: 2,
    effect: 'block 8',
    description: '获得 8 点防御。',
  ),

  'strike_1': CardData(
    id: 'strike_1',
    name: '数据冲击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.classic,
    cost: 1,
    level: 1,
    effect: 'damage 6',
    description: '对目标系统造成 6 点冲击。',
  ),
  'strike_2': CardData(
    id: 'strike_2',
    name: '数据清除',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.classic,
    cost: 1,
    level: 3,
    effect: 'damage 12',
    description: '对目标系统造成 12 点伤害。',
  ),
  'multi_effect_card': CardData(
    id: 'multi_effect_card',
    name: '复合指令集',
    type: CardType.routine,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 2,
    level: 3,
    effect: 'damage 8; block 5; draw 2',
    description: '造成 8 点冲击，获得 5 点防火墙加固，并读取 2 个数据包。',
  ),
  'defend_1': CardData(
    id: 'defend_1',
    name: '加密协议',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.classic,
    cost: 1,
    level: 1,
    effect: 'block 5',
    description: '获得 5 点防火墙加固。',
  ),
  'defend_2': CardData(
    id: 'defend_2',
    name: '硬核防火墙',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 2,
    level: 2,
    effect: 'block 15',
    description: '获得 15 点防火墙加固。',
  ),
  'bash': CardData(
    id: 'bash',
    name: '系统中断',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 2,
    level: 2,
    effect: 'damage 8; vulnerable 2',
    description: '造成 8 点冲击，并施加 2 层漏洞暴露。',
  ),
  'heavy_blade': CardData(
    id: 'heavy_blade',
    name: '暴力破解',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 2,
    level: 3,
    effect: 'damage 14; strength 2',
    description: '造成 14 点冲击，获得 2 点算力提升。',
  ),
  'double_hit': CardData(
    id: 'double_hit',
    name: '并行冲击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 1,
    level: 2,
    effect: 'damage 4; damage 4',
    description: '执行两次冲击，每次造成 4 点伤害。',
  ),
  'ritual': CardData(
    id: 'ritual',
    name: '递归算法',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 0,
    level: 3,
    effect: 'strength 3; self_damage 1',
    description: '获得 3 点算力，但会导致系统过热造成 1 点自损伤。',
  ),
  'sneaky_strike': CardData(
    id: 'sneaky_strike',
    name: '漏洞扫描',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 1,
    level: 1,
    effect: 'damage 4; draw 1',
    description: '造成 4 点冲击，并读取 1 个数据包。',
  ),
  'defensive_stance': CardData(
    id: 'defensive_stance',
    name: '安全模式',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 1,
    level: 2,
    effect: 'block 5; strength 1',
    description: '获得 5 点防火墙，并提升 1 点算力。',
  ),
  'desperate_power': CardData(
    id: 'desperate_power',
    name: '紧急过载',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 0,
    level: 4,
    effect: 'strength 30 self_damage 5',
    description: '大幅提升 30 点算力，但系统负载过高造成 5 点自损伤。',
  ),
  'bludgeon': CardData(
    id: 'bludgeon',
    name: '逻辑炸弹',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.overload,
    cost: 3,
    level: 4,
    effect: 'damage 32',
    description: '投放逻辑炸弹，对目标造成 32 点巨大冲击。',
  ),
  'reaper': CardData(
    id: 'reaper',
    name: '资源回收',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 4,
    level: 5,
    effect: 'damage 6; heal 20',
    description: '造成 6 点冲击，并从目标回收资源修复 20 点系统生命值。',
  ),
  'burning_slash': CardData(
    id: 'burning_slash',
    name: '超频攻击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.overload,
    cost: 1,
    level: 2,
    effect: 'damage 9; self_damage 2',
    description: '超频执行攻击造成 9 点冲击，自身受损 2 点。',
  ),
  'ignite': CardData(
    id: 'ignite',
    name: '核心激活',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 0,
    level: 1,
    effect: 'strength 2; self_damage 2',
    description: '激活核心提升 2 点算力，受损 2 点。',
  ),
  'weaken': CardData(
    id: 'weaken',
    name: '性能限制',
    type: CardType.routine,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 1,
    level: 3,
    effect: 'weak 2',
    description: '限制目标性能，施加 2 层虚弱状态。',
  ),
  'curse_mark': CardData(
    id: 'curse_mark',
    name: '恶意标记',
    type: CardType.routine,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 1,
    level: 3,
    effect: 'vulnerable 2; weak 1',
    description: '在目标系统留下恶意标记，施加 2 层漏洞暴露和 1 层虚弱。',
  ),
  'fade_step': CardData(
    id: 'fade_step',
    name: '隐匿跳跃',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 1,
    level: 1,
    effect: 'block 6; draw 1',
    description: '获得 6 点防火墙，并读取 1 个数据包。',
  ),
  'core_module': CardData(
    id: 'core_module',
    name: '底层内核',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.industrial,
    cost: 1,
    level: 1,
    effect: 'strength 1',
    description: '加载底层内核模块，提升 1 点算力。',
  ),
  'assemble': CardData(
    id: 'assemble',
    name: '指令编译',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.quantum,
    cost: 1,
    level: 1,
    effect: 'draw 2',
    description: '编译指令流，读取 2 个数据包。',
  ),
  'overclock': CardData(
    id: 'overclock',
    name: '频率超限',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 0,
    level: 1,
    effect: 'energy 1; self_damage 4',
    description: '强行提升系统频率，获得 1 点带宽，受损 4 点。',
  ),
  'phase_shift': CardData(
    id: 'phase_shift',
    name: '进程迁移',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 1,
    level: 2,
    effect: 'block 7; draw 1',
    description: '迁移关键进程，获得 7 点防火墙并读取 1 个数据包。',
  ),
  'peek_future': CardData(
    id: 'peek_future',
    name: '预读缓冲区',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.quantum,
    cost: 0,
    level: 1,
    effect: 'draw 1',
    description: '预读数据流，读取 1 个数据包。',
  ),
  'vanish': CardData(
    id: 'vanish',
    name: '清除足迹',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 2,
    level: 3,
    effect: 'block 18',
    description: '清除系统访问足迹，获得 18 点防火墙。',
  ),
  'survivor': CardData(
    id: 'survivor',
    name: '容错机制',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 0,
    level: 3,
    effect: 'block 5; draw 1',
    description: '激活容错机制，获得 5 点防火墙并读取 1 个数据包。',
  ),
  'dualcast': CardData(
    id: 'dualcast',
    name: '双线程执行',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.quantum,
    cost: 1,
    level: 3,
    effect: 'draw 2; energy 1',
    description: '开启双线程，读取 2 个数据包并获得 1 点带宽。',
  ),
  'energy_boost': CardData(
    id: 'energy_boost',
    name: '带宽扩容',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.quantum,
    cost: 0,
    level: 2,
    effect: 'energy 1',
    description: '扩容系统带宽，获得 1 点额外带宽。',
  ),
  'eruption': CardData(
    id: 'eruption',
    name: '数据喷发',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.overload,
    cost: 3,
    level: 2,
    effect: 'damage 20',
    description: '瞬间喷发海量数据，对目标造成 20 点冲击。',
  ),
  // Lv2 卡牌
  'data_storm': CardData(
    id: 'data_storm',
    name: '数据风暴',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 2,
    level: 2,
    effect: 'damage 5; damage 5; damage 5',
    description: '发起三次数据冲击，每次造成 5 点伤害。',
  ),
  'hardened_shell': CardData(
    id: 'hardened_shell',
    name: '强化外壳',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 2,
    level: 2,
    effect: 'block 15 ',
    description: '部署强化外壳，获得 15 点防火墙。',
  ),
  'neural_interface': CardData(
    id: 'neural_interface',
    name: '神经接口',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.quantum,
    cost: 2,
    level: 3,
    effect: 'draw 3; energy 1',
    description: '建立神经连接，读取 3 个数据包并获得 1 点带宽。',
  ),
  'predator_program': CardData(
    id: 'predator_program',
    name: '捕食者程序',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 3,
    level: 2,
    effect: 'damage 12; heal 5',
    description: '运行捕食者程序，造成 12 点冲击并回收 5 点系统生命值。',
  ),
  'logic_gate': CardData(
    id: 'logic_gate',
    name: '逻辑锁死',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.industrial,
    cost: 2,
    level: 3,
    effect: 'damage 10; vulnerable 3',
    description: '对目标进行逻辑锁死，造成 10 点冲击并施加 3 层漏洞暴露。',
  ),
  'malware_injection': CardData(
    id: 'malware_injection',
    name: '恶意代码注入',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 1,
    level: 3,
    effect: 'damage 5; curse 2',
    description: '注入一段恶意代码，造成 5 点冲击并施加 2 层恶意代码（每层使目标多受 2 点伤害）。',
  ),
  // Lv3 卡牌
  'singularity': CardData(
    id: 'singularity',
    name: '数据奇点',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 4,
    level: 4,
    effect: 'damage 45',
    description: '创造一个数据奇点，对目标造成 45 点毁灭性冲击。',
  ),
  'mainframe_hijack': CardData(
    id: 'mainframe_hijack',
    name: '主机劫持',
    type: CardType.routine,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 3,
    level: 5,
    effect: 'damage 20; draw 4; energy 2',
    description: '劫持对方主机，造成 20 点冲击，读取 4 个数据包并获得 2 点带宽。',
  ),
  'absolute_zero_ice': CardData(
    id: 'absolute_zero_ice',
    name: '绝对零度冰墙',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 3,
    level: 4,
    effect: 'block 30 ; sturdy 3',
    description: '部署绝对零度防御系统。',
  ),
  'infinite_loop': CardData(
    id: 'infinite_loop',
    name: '无限循环',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 2,
    level: 3,
    effect: 'strength 5; self_damage 1',
    description: '强行开启无限循环模式，提升 5 点算力，但导致系统严重过热受损 1 点。',
  ),
  'system_reboot': CardData(
    id: 'system_reboot',
    name: '系统重装',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 4,
    level: 4,
    effect: 'heal 15; block 20; sturdy 2',
    description: '执行系统重装流程，修复 15 点生命值并部署 20 点防火墙，同时提升 2 点坚固。',
  ),
  'supercomputer_f': CardData(
    id: 'supercomputer_f',
    name: '超算行动-失败',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 3,
    level: 4,
    effect: 'strength 99; self_damage 60',
    description: '强行开启超算行动，提升99点算力，但导致系统严重过热受损60点。',
  ),
  'supercomputer': CardData(
    id: 'supercomputer',
    name: '超算行动',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 3,
    level: 5,
    effect: 'strength 9; temp_strength 90',
    description: '开启超算行动，提升99点算力。',
  ),
  'prevent_penetration': CardData(
    id: 'prevent_penetration',
    name: '阻止渗透',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.industrial,
    cost: 4,
    level: 5,
    effect: 'block 999',
    description: '部署终极防火墙。',
  ),
  'data_broadcast': CardData(
    id: 'data_broadcast',
    name: '数据广播',
    type: CardType.exploit,
    target: CardTarget.all,
    suite: CardSuite.classic,
    cost: 1,
    level: 2,
    effect: 'damage 6',
    description: '对所有敌方进程广播冲击信号，造成 6 点伤害。',
  ),
  'matrix_sweep': CardData(
    id: 'matrix_sweep',
    name: '矩阵清理',
    type: CardType.exploit,
    target: CardTarget.all,
    suite: CardSuite.secure,
    cost: 2,
    level: 3,
    effect: 'damage 9; weak 1',
    description: '清理矩阵内的非法进程，对全体造成 9 点伤害并施加 1 层虚弱。',
  ),
  'global_format': CardData(
    id: 'global_format',
    name: '全域格式化',
    type: CardType.exploit,
    target: CardTarget.all,
    suite: CardSuite.overload,
    cost: 3,
    level: 3,
    effect: 'damage 22; vulnerable 2',
    description: '执行全域格式化指令，对全体造成 22 点伤害并施加 2 层漏洞暴露。',
  ),
  
  'block_wall': CardData(
    id: 'block_wall',
    name: '绝对零度冰墙',
    type: CardType.encryption,
    target: CardTarget.all,
    suite: CardSuite.quantum,
    cost: 0,  
    level: 3,
    effect: 'block 3; curse 1; sturdy 2',
    description: '部署绝对零度防御系统，并对所有敌人进行量子标记。',
  ),

  // --- 补全卡牌 (几何 & 虚行) ---

  // 几何 (jihe) 扩展
  'repair_module': CardData(
    id: 'repair_module',
    name: '修复模块',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.industrial,
    cost: 1,
    level: 4,
    effect: 'heal 4; block 4',
    description: '运行底层修复协议，恢复 4 点生命值并获得 4 点防御。',
  ),
  'shield_boost': CardData(
    id: 'shield_boost',
    name: '护盾增压',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.industrial,
    cost: 2,
    level: 3,
    effect: 'block 12; strength 1',
    description: '对防御模块进行增压，获得 12 点防御并提升 1 点算力。',
  ),

  // 虚行 (xuxing) 扩展
  'quantum_burst': CardData(
    id: 'quantum_burst',
    name: '量子爆发',
    type: CardType.exploit,
    target: CardTarget.all,
    suite: CardSuite.quantum,
    cost: 2,
    level: 3,
    effect: 'damage 7; curse 1',
    description: '引发量子连锁反应，对全体造成 7 点伤害并施加 1 层恶意代码。',
  ),
  'chaos_logic': CardData(
    id: 'chaos_logic',
    name: '混沌逻辑',
    type: CardType.routine,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 1,
    level: 3,
    effect: 'weak 1; vulnerable 1; curse 1',
    description: '向目标注入混沌算法，施加 1 层虚弱、漏洞和恶意代码。',
  ),
  'chaos_first': CardData(
    id: 'chaos_first',
    name: '混沌起源',
    type: CardType.routine,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 2,
    level: 5,
    effect: 'weak 3; vulnerable 3; curse 3',
    description: '向目标注入混沌算法，施加 3 层虚弱、漏洞和恶意代码。',
  ),
  'glitch_step': CardData(
    id: 'glitch_step',
    name: '故障步进',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.quantum,
    cost: 0,
    level: 3,
    effect: 'block 4; draw 1',
    description: '利用系统微小故障进行位移，获得 4 点防御并读取 1 个数据包。',
  ),
  'void_slash': CardData(
    id: 'void_slash',
    name: '虚空斩击',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.quantum,
    cost: 1,
    level: 2,
    effect: 'damage 10',
    description: '从虚空维度发动的斩击，造成 10 点伤害。',
  ),
  'fa_weaken': CardData(
  id: 'fa_weaken',
  name: '协议降级',
  type: CardType.routine,
  target: CardTarget.enemy,
  suite: CardSuite.secure,
  cost: 1,
  level: 3,
  effect: 'weak 2',
  description: '使一个敌人获得 2 层虚弱。',
),
  'fa_cascade': CardData(
    id: 'fa_cascade',
    name: '连锁崩解',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.overload,
    cost: 2,
    level: 3,
    effect: 'damage 10; vulnerable 2',
    description: '对一个敌人造成 10 点伤害并施加 2 层易伤。',
  ),
  // === 新增：生命上限调整 & 坚固相关卡牌 ===
  'vital_patch': CardData(
    id: 'vital_patch',
    name: '完整性补丁',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 4,
    level: 4,
    effect: 'max_hp_up 4; heal 4',
    description: '安装完整性补丁，提升 4 点生命上限并立即修复 4 点。',
  ),
  'capacity_upgrade': CardData(
    id: 'capacity_upgrade',
    name: '内核扩容',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.industrial,
    cost: 2,
    level: 3,
    effect: 'max_hp_up 1',
    description: '扩容底层内核结构，永久提升 1 点生命上限。',
  ),
  'capacity_trim': CardData(
    id: 'capacity_trim',
    name: '内核瘦身',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.overload,
    cost: 0,
    level: 3,
    effect: 'max_hp_down 2; energy 3',
    description: '减少冗余模块以换取性能，生命上限 -2 并获得 3 点带宽。',
  ),
  'fortify_wall': CardData(
    id: 'fortify_wall',
    name: '加固壁垒',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.industrial,
    cost: 1,
    level: 3,
    effect: 'block 10; sturdy 2',
    description: '对防御壁垒进行加固，获得 10 点防御与 2 层坚固。',
  ),
  'nano_plating': CardData(
    id: 'nano_plating',
    name: '纳米涂层',
    type: CardType.module,
    target: CardTarget.self,
    suite: CardSuite.secure,
    cost: 1,
    level: 3,
    effect: 'sturdy 5',
    description: '为外壳覆以纳米涂层，获得 5 层坚固，使护盾在回合结束保留。',
  ),

  // --- 独特：恶魔系列 ---
  'demon_breath': CardData(
    id: 'demon_breath',
    name: '恶魔之息',
    type: CardType.exploit,
    target: CardTarget.all,
    suite: CardSuite.demon,
    cost: 3,
    level: 999, // Lv 为 ? 在显示逻辑中处理
    effect: 'damage 66; curse 3; weak 3',
    description: '释放来自深渊的威压。对全体造成 66 点伤害，施加 3 层恶意代码和虚弱。',
  ),
  'demon_embrace': CardData(
    id: 'demon_embrace',
    name: '恶魔之拥',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.demon,
    cost: 2,
    level: 999,
    effect: 'block 40; strength 5; self_damage 5',
    description: '接受恶魔的拥抱。获得 40 点防御和 5 点算力，但自损 5 点生命。',
  ),
  'demon_contract': CardData(
    id: 'demon_contract',
    name: '灵魂契约',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.demon,
    cost: 0,
    level: 999,
    effect: 'energy 3; draw 5; max_hp_down 2',
    description: '签署不可逆的契约。获得 3 点能量并摸 5 张牌，但永久失去 2 点生命上限。',
  ),

  // --- 独特：神圣系列 ---
  'holy_light': CardData(
    id: 'holy_light',
    name: '神圣之光',
    type: CardType.exploit,
    target: CardTarget.all,
    suite: CardSuite.holy,
    cost: 2,
    level: 999,
    effect: 'damage 30; vulnerable 2; weak 2',
    description: '净化一切的神圣光芒。对全体造成 30 点伤害，施加 2 层脆弱和虚弱。',
  ),
  'holy_barrier': CardData(
    id: 'holy_barrier',
    name: '神圣壁垒',
    type: CardType.encryption,
    target: CardTarget.self,
    suite: CardSuite.holy,
    cost: 2,
    level: 999,
    effect: 'block 30; sturdy 3; heal 5',
    description: '不可逾越的神圣防线。获得 30 点防御，3 层坚固，并恢复 5 点生命。',
  ),
  'holy_blessing': CardData(
    id: 'holy_blessing',
    name: '神圣祝福',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.holy,
    cost: 0,
    level: 999,
    effect: 'energy 2; draw 2',
    description: '获得神圣的指引。获得 2 点带宽，抽取 2 张卡牌。',
  ),
  'holy_judgment': CardData(
    id: 'holy_judgment',
    name: '神圣审判',
    type: CardType.exploit,
    target: CardTarget.enemy,
    suite: CardSuite.holy,
    cost: 2,
    level: 999,
    effect: 'damage 50; vulnerable 3; weak 3',
    description: '降下神圣的审判。对目标造成 50 点伤害，并施加 3 层漏洞暴露与虚弱。',
  ),
  'holy_salvation': CardData(
    id: 'holy_salvation',
    name: '神圣救赎',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.holy,
    cost: 2,
    level: 999,
    effect: 'heal 20; max_hp_up 5',
    description: '神圣力量的救赎。恢复 20 点生命值，并永久提升 5 点生命上限。',
  ),
  'holy_nova': CardData(
    id: 'holy_nova',
    name: '神圣新星',
    type: CardType.exploit,
    target: CardTarget.all,
    suite: CardSuite.holy,
    cost: 2,
    level: 999,
    effect: 'damage 20; block 20',
    description: '神圣能量的爆发。对全体敌人造成 20 点冲击，并获得 20 点防火墙加固。',
  ),
  'holy_ascension': CardData(
    id: 'holy_ascension',
    name: '神圣升华',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.holy,
    cost: 4,
    level: 999,
    effect: 'strength 5; energy 1',
    description: '灵魂的升华。获得 5 点算力，且每回合额外获得 1 点带宽。',
  ),
  'holy_sanctuary': CardData(
    id: 'holy_sanctuary',
    name: '神圣避难所',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.holy,
    cost: 2,
    level: 999,
    effect: 'block 40; sturdy 2',
    description: '构筑神圣的避难所。获得 40 点防火墙加固和 2 层坚固。',
  ),
  'holy_purification': CardData(
    id: 'holy_purification',
    name: '神圣净化',
    type: CardType.routine,
    target: CardTarget.self,
    suite: CardSuite.holy,
    cost: 1,
    level: 999,
    effect: 'block 15; draw 3',
    description: '净化心灵的阴霾。获得 15 点防火墙加固并抽取 3 张卡牌。',
  ),
};
